### ISSUE TITLE
Feature request: information on name mapping

### ISSUE THREAD

**Issue by werner-matthias** [u-fischer/newpax#20]
Currently, newpax doesn't export the original names of link destinations but but renumbers them.
It would be nice to get an information of the mapping between original and new name.

#### Background:
One application case could be common tables of contents for embedded pdfs, see [https://tex.stackexchange.com/q/682625/12606](https://tex.stackexchange.com/q/682625/12606).

**Comment by briha** [comment]
I am attempting the same thing, and hadn't seen your StackExchange post/this issue. I have managed to modify newpax so that it does export all the destinations, in addition to the ones it is just using for linking. I am taking the original name, prefixed by <filename>.newpax., so that no conflicts with destinations in the parent document occur. https://github.com/u-fischer/newpax/pull/22 makes that change. To have the destinations actually present in your file, they need to be requested with `\NEWPAX@DestReq`, where the first argument is the `file.newpax` and the second is the name of the destination (i.e., the number for the original ones, or the prefix + original destination name for all others).

I haven't got the table of contents working yet, however, so please let me know if you figure that out!

**Comment by briha** [comment]
Ok, with the current changes in #22 it works with the following MWE:

`doc-use-newpax.tex`
```latex
\DocumentMetadata{uncompress}
\documentclass{scrarticle}

\usepackage{pdfpages,xcolor}

\usepackage{hyperref}
\hypersetup{linkbordercolor=blue}
\usepackage{kantlipsum}

% \makeatletter
% \input{out/doc-input/doc-input.aux}
% \makeatother
\usepackage{newpax}
\directlua
{
  require("newpax")
  newpax.writenewpax("doc-input")
}


\makeatletter

\def\altcontentsline#1#2#3#4{
    \edef\@NEWPAX@PDFDEST@NAME{NEWPAX@\NEWPAX@file @#4@\csname l_@@_destsuffix_tl\endcsname}
    \protected@write\@auxout{}{%
        \string\NEWPAX@DestReq{\NEWPAX@file}{#4}%
    }%
    \edef\addtocontentsX{{\string #1}{\string #2}{\string #3}{\@NEWPAX@PDFDEST@NAME}}%
    \addtocontents{toc}{\string\contentsline\addtocontentsX}%
}


% #1 = file name, #2 = target file
\def\IncludeIncludedFileMeta#1#2{
    \begingroup%
    \def\NEWPAX@file{#1.newpax}
    \let\old@contentsline\contentsline
    \let\contentsline\altcontentsline
    \input{#1.#2}
    \let\contentsline\old@contentsline
    \endgroup%
}
\makeatother

\begin{document}
\tableofcontents

\section{Main}
\kant[1-3]
\section{Next}
\kant[4]

\IncludeIncludedFileMeta{doc-input}{toc}
\includepdf[pages=-]{doc-input}

\setcounter{section}{5}
\section{Last}
\kant[5-7]

\end{document}
```

`doc-input.tex`
```latex
\DocumentMetadata{uncompress}
\documentclass{article}
\usepackage{hyperref}

\hypersetup{pdfborderstyle={/S/U/W 1},
   pdfauthor=Author,pdftitle=title,pdfcreator=creator}

\usepackage{kantlipsum}
\begin{document}

\makeatletter
% from \@starttoc, but without re-reading, creates toc file 
\newwrite\tf@toc
\immediate\openout\tf@toc\jobname.toc\relax
\makeatother

\setcounter{section}{2} % to ensure correct section numbers
\setcounter{page}{3}    % ... and page numbers

\section{Section 3}\label{sec}
See Section~\ref{sec2}\par
\kant[3-6]
\section{Section 4}\label{sec2}
\subsection{Section 4.1}\label{2-1}
\kant[8]
\section{Section 5}\label{sec3}
\kant[9]

\end{document} 
```

**Comment by tobiasBora** [comment]
Apparently, this issue might help to solve https://tex.stackexchange.com/questions/695277/clickable-includegraphics-for-cross-reference-data in order to cache latex code with references… As of right now I am not sure if the problem is from my original compilation (that displays a scary warning `name{section.2} has been referenced but does not exist, 
replaced by a fixed one`… maybe I should also export some macro and not just the content of the aux file?) or from newpax, but I’ll keep an eye on this issue.

**Comment by briha** [comment]
For it to work, you need to use the newpax version of https://github.com/u-fischer/newpax/pull/22, which is a patch to export every pdf destination.
Am 6. Sept. 2023, 22:09 +0200 schrieb Tobias Bora ***@***.***>:

**Comment by tobiasBora** [comment]
Awesome, I can confirm it works this way! Thanks a lot! Hope the PR will be merged soon.

**Comment by u-fischer** [comment]
I pushed a new version to CTAN which should resolve the issue. I have added an answer to the tex.sx question about how to use it 

https://tex.stackexchange.com/a/695715/2388

I didn't use the PR as I wanted more control over the included destinations and less duplications.
