### ISSUE TITLE
Respect custom output directory

### ISSUE THREAD

**Issue by briha** [u-fischer/newpax#21]
When compiling using latexmk/lualatex one can set a directory for all the auxiliary files, which is very helpful to keep the directory with main latex source clean. Newpax is currently ignoring that setting, and just dumping the .newpax/.pax in the main directory.

**Comment by u-fischer** [comment]
Sorry no, I will not implement that. I'm actively discouraging people to use out output-directory for various reasons (see e.g. https://tex.stackexchange.com/a/673007/2388) and it would be a maintenance nightmare to have to check for the various command line options.  If you want a complex build system use make or l3build or arara or latexmk to move the files around.

**Comment by briha** [comment]
Arguing against supporting something, just because other packages also don't support it, seems like a very regressive attitude to me. I, personally, have not had any issues with a dedicated out directory that I couldn't solve, and I don't see why I should accept my entire directory to be littered with a substantial number of temporary files, that I have zero direct interactions with.
Also, for the record, I am using latexmk and everything but newpax is respecting the options I pass to latexmk in terms of output directory. For that reason, I have also not ever had to look into how to make latexmk move anything so far.

**Comment by u-fischer** [comment]
I'm not supporting it because over the years I have seen to many question on tex.sx and elsewhere where a build failed because of a new combination of tools or packages not finding their files. 

I'm not supporting it because finding out how to detect these command line options and to redirect the writing of files reliably for all tex systems and for all OS systems  would cost a lot of time and effort (and many cases I couldn't test properly).

So when I don't want to compile in the current folder, I setup l3build to move the files to a temp folder. This is how e.g. the documentation of newpax and other packages are compiled.

> For that reason, I have also not ever had to look into how to make latexmk move anything so far.

If it is so important for you, it should be worth the time and effort to learn this.

**Comment by briha** [comment]
> If it is so important for you, it should be worth the time and effort to learn this.

I get your standpoint. It looks like either I was just lucky or my latex use was too superficial. I'll definitely have a look at that, although the number of files is usually the problem – and right now, it is only one .newpax, which isn't a huge deal.
